### PR TITLE
Fix FPs on S1656

### LINKED ISSUE #132: FP on S1656 SelfAssignment
There are two kinds of FP`s
 - declaration is never self-assignment, it's shadowing `a := a`
 - compound assignment is not handled properly `a += a`

### PR DESCRIPTION
**Pull request by saberduck**
Fix #132

### CODE REVIEW

File: common-rule-engine/src/main/java/org/sonar/uast/UastNode.java [hunk 1]
```diff
@@ -184,6 +186,19 @@ private void joinTokens(StringBuilder sb, SourcePos pos) {
     }
   }
 
+  public boolean is(Kind... kinds) {
```
Comment (ghost) [inline common-rule-engine/src/main/java/org/sonar/uast/UastNode.java:189]: I wonder about this method. Are we really going to call it with multiple kinds? It sounds counter-intuitive to me, while I can perfectly see the `isNot(...)` use case. I would prefer to have it with a single kind argument, and have the loop in the `isNot()` method.

**Review by ghost — APPROVED** [review]
Except for method `is(...)` which I think we can fix later, LGTM.

File: common-rule-engine/src/main/java/org/sonar/uast/UastNode.java (hunk 1 above)
Comment (saberduck) [reply common-rule-engine/src/main/java/org/sonar/uast/UastNode.java:189]: @m-g-sonar I understand your point, we can change it when we see there is indeed no need for it. So far it's not used
